import Foundation

/// Domains pulled from yt-dlp's own extractor list (`yt-dlp --list-extractors`,
/// resolved to a real domain via each extractor's test URL, falling back to a
/// regex match against its `_VALID_URL` pattern where there's no test case).
/// This is a soft, informational check, not a hard gate — yt-dlp itself has
/// no real "unsupported domain" concept: any http(s) link it doesn't
/// recognize falls through to its generic page-scraping extractor and it
/// tries anyway. A missing domain here just means "not one of the ~1150
/// sites with their own dedicated parser" — worth a gentle heads-up, never a
/// blocked download (a live network probe for this was tried once already
/// and removed for giving false negatives — see CLAUDE.md).
enum SupportedSites {
    static func isKnown(host: String) -> Bool {
        var h = host.lowercased()
        if h.hasPrefix("www.") { h.removeFirst(4) }
        if domains.contains(h) { return true }
        // Walk up subdomains: m.facebook.com / touch.facebook.com should
        // still match a plain "facebook.com" entry.
        var parts = h.split(separator: ".")
        while parts.count > 2 {
            parts.removeFirst()
            if domains.contains(parts.joined(separator: ".")) { return true }
        }
        return false
    }

    static let domains: Set<String> = [
    "10.com.au", "17.live", "1news.co.nz", "1tv.ru", "1und1.tv", "20min.ch",
    "247sports.com", "24tv.ua", "2m.ma", "365.rtvslo.si", "3cat.cat", "3sat.de",
    "3speak.tv", "4tube.com", "5-tv.ru", "56.com", "7plus.com.au", "9gag.com",
    "9news.com.au", "9now.com.au", "abc.com", "abc.net.au", "abc7news.com", "abcnews.go.com",
    "abema.tv", "academicearth.org", "academymel.online", "acast.com", "acfun.cn", "adrianvonziegler.bandcamp.com",
    "adult.noodlemagazine.com", "adultswim.com", "aeon.co", "agalega.gal", "ahctv.com", "aitube.kz",
    "alibaba.com", "allocine.fr", "allstar.gg", "allvod.sbs.co.kr", "aloula.sba.sa", "alphaporno.com",
    "altcensored.com", "amadeus.tv", "amara.org", "amazon.co.uk", "amazon.com", "amazon.in",
    "amc.com", "americastestkitchen.com", "amp.twimg.com", "anderetijden.nl", "andrei-bt.livejournal.com", "angel.com",
    "animalplanet.com", "animationdigitalnetwork.com", "animemanga.popcorntv.it", "ant1news.gr", "antenna.gr", "aol.com",
    "aparat.com", "aph.gov.au", "api.frontendmasters.com", "api.nexx.cloud", "api.screen9.com", "api.simplecast.com",
    "api.soundcloud.com", "api.spreaker.com", "app.curiositystream.com", "app.cybrary.it", "app.idagio.com", "app.itpro.tv",
    "app.lecturio.com", "app.ustudio.com", "app.veo.co", "archive.org", "ardaudiothek.de", "ardmediathek.de",
    "areena.yle.fi", "arhiiv.err.ee", "art19.com", "arte.sky.it", "arte.tv", "asiancrush.com",
    "asobichannel.asobistore.jp", "asobistage.asobistore.jp", "atresplayer.com", "atscaleconference.com", "au.bbcollab.com", "audi-mediacenter.com",
    "audioboom.com", "audiodraft.com", "audiomack.com", "audius.co", "audycje.tokfm.pl", "balkans.aljazeera.net",
    "banbye.com", "bandcamp.com", "bandlab.com", "banned.video", "bbc.co.uk", "bbc.com",
    "bbv-tv.net", "beacon.tv", "beatport.com", "beeg.com", "behindkink.com", "best-vod.umn.cdn.united.cloud",
    "bet.com", "beta.prx.org", "bfmtv.com", "bibeltv.de", "biblewayng.mixlr.com", "bigo.tv",
    "bild.de", "bilibili.com", "bilibili.tv", "biography.com", "bitchute.com", "bl.webcaster.pro",
    "blazo.bandcamp.com", "bleacherreport.com", "blerp.com", "blogger.com", "blogs.elpais.com", "bloomberg.com",
    "bndestem.nl", "boosty.to", "bostonglobe.com", "boxcast.tv", "bpb.de", "br.de",
    "brainpop.com", "bravotv.com", "breitbart.com", "bsky.app", "bt.no", "btvplus.bg",
    "budem.mave.digital", "buffalobills.com", "build.microsoft.com", "bundesliga.com", "burn7.newgrounds.com", "buzzfeed.com",
    "bx1.be", "byutv.org", "c-span.org", "c.brightcove.com", "cam4.com", "camfm.co.uk",
    "cammodels.com", "camsoda.com", "canal1.com.co", "canalalpha.ch", "canalc2.tv", "canalsurmas.es",
    "cbc.ca", "cbs.com", "cbsnews.com", "cbssports.com", "cc.com", "cda.pl",
    "cdn.embedly.com", "cdn.ethnos.gr", "cdn.viqeo.tv", "cellebrite.com", "ceskatelevize.cz", "charlierose.com",
    "chaturbate.com", "chilloutzone.net", "chzzk.naver.com", "cielotv.it", "cinemax.com", "cinetecamilano.it",
    "ciscolive.cisco.com", "cjsw.com", "classes.brilliantpala.org", "classics.nascar.com", "clip.rs", "clipchamp.com",
    "clips.abcotvs.com", "clips.twitch.tv", "closertotruth.com", "clubdam.com", "clubic.com", "clyp.it",
    "cnbc.com", "cnn.com", "cnn.iprima.cz", "cnnindonesia.com", "commons.wikimedia.org", "conanclassic.com",
    "consent.youtube.com", "content.jwplatform.com", "content.uplynk.com", "cooking.nytimes.com", "cookingchanneltv.com", "coub.com",
    "cozy.tv", "cp24.com", "cp44293.edgefcs.net", "cpac.ca", "cracked.com", "craftsy.com",
    "croatian.film", "crowdbunker.com", "crtvg.es", "ctvnews.ca", "cu.ntv.co.jp", "cu.tbs.co.jp",
    "cultureunplugged.com", "curiositystream.com", "cursos.alura.com.br", "cwwp2.dot.ca.gov", "d.tube", "dagbladet.no",
    "dagelijksekost.een.be", "dailymail.co.uk", "dailymotion.com", "dailywire.com", "dangalplay.com", "dbtg.tv",
    "dctp.tv", "de.bongacams.com", "de.hgtv.com", "demo.hosted.panopto.com", "democracynow.org", "demosubdomain.webex.com",
    "destinationamerica.com", "deutschlandfunk.de", "deviceids-medp.wdr.de", "dhm.de", "digitalconcerthall.com", "discogs.com",
    "discoverylife.com", "discoveryplus.com", "discoveryplus.in", "discoveryplus.it", "dlive.tv", "dmax.de",
    "dood.to", "douyin.com", "douyu.com", "dplay.se", "dr.dk", "drive.google.com",
    "dropbox.com", "drtalks.com", "drtuber.com", "dumpert.nl", "duoplay.ee", "dw.com",
    "ebaumsworld.com", "ebay.com", "ec.europa.eu", "economist.zoom.us", "egghead.io", "eggs.mu",
    "elearn.brilliantpala.org", "ell.brainpop.com", "elonet.finna.fi", "eltrecetv.com.ar", "embed.cloudflarestream.com", "embed.cloudycdn.services",
    "embed.crooksandliars.com", "embed.life.ru", "embed.nexx.cloud", "embed.snagfilms.com", "embed.ted.com", "embed.vhx.tv",
    "empflix.com", "en.roya.tv", "epicon.in", "epidemicsound.com", "eporner.com", "erocast.me",
    "eroprofile.com", "ert.gr", "ertflix.gr", "esp.brainpop.com", "espn.com", "espn.go.com",
    "espncricinfo.com", "ethnos.gr", "ettu.tv", "europeantour.com", "eurosport.com", "eurosport.onet.pl",
    "euscreen.eu", "event.on24.com", "events7.mediasite.com", "evt.dispeak.com", "expressen.se", "facebook.com",
    "fancode.com", "fast.wistia.net", "fathom.video", "faz.net", "fc-zenit.ru", "feed.theplatform.com",
    "fifa.com", "filmarchiv.at", "filmon.com", "filmweb.no", "fivethirtyeight.com", "flextv.co.kr",
    "flickr.com", "floatplane.com", "fm4.orf.at", "footyroom.com", "formula1.com", "fox.com",
    "fox9.com", "foxnews.com", "foxsports.com", "fptplay.vn", "fr.brainpop.com", "framatube.org",
    "francaisfacile.rfi.fr", "france.tv", "francetvinfo.fr", "freesound.org", "freespeech.org", "freetv.com",
    "frontendmasters.com", "ft.dk", "funk.net", "funker530.com", "fux.com", "fuyin.tv",
    "g1.globo.com", "gab.com", "gaia.com", "gamedev.tv", "gamejolt.com", "gamespot.com",
    "gamestar.de", "gaskrank.tv", "gazeta.ru", "gbnews.com", "gdcvault.com", "gem.cbc.ca",
    "genius.com", "germanupa.de", "gettr.com", "giantbomb.com", "globalplayer.com", "globoplay.globo.com",
    "gmanetwork.com", "gns3.teachable.com", "go.discovery.com", "go.tlc.com", "godtube.com", "goodgame.ru",
    "gopro.com", "gotostage.com", "gronkh.tv", "groupon.com", "haleynahman.substack.com", "harpodeon.com",
    "hbo.com", "hearthis.at", "heise.de", "hellporno.com", "help.senate.gov", "helsinkikanava.fi",
    "hessenschau.de", "hetklokhuis.nl", "hgtv.ca", "hgtv.com", "hidive.com", "historicfilms.com",
    "history.com", "hitrecord.org", "hitsmediaweb.h-its.org", "hollywoodreporter.com", "holodex.net", "hotnewhiphop.com",
    "hotstar.com", "how-to-video.vids.io", "howtovideos.hosted.panopto.com", "href.li", "hrti.hrt.hr", "hse.de",
    "html5-player.libsyn.com", "huajiao.com", "hungama.com", "huya.com", "hypem.com", "hytale.com",
    "ici.radio-canada.ca", "ici.tou.tv", "iflix.com", "iframe.dacast.com", "iframe.mediadelivery.net", "ign.com",
    "iheart.com", "il.brainpop.com", "ilpost.it", "iltalehti.fi", "imdb.com", "imgur.com",
    "ina.fr", "inc.com", "indavideo.hu", "infoq.com", "instagram.com", "internazionale.it",
    "investigationdiscovery.com", "iptv.glattvision.ch", "iptv.orf.at", "iq.com", "iqiyi.com", "israelnationalnews.com",
    "itv.com", "ivi.ru", "ivideon.com", "iview.abc.net.au", "ivoox.com", "iwara.tv",
    "ixigua.com", "jamendo.com", "jedynka.polskieradio.pl", "jeuxvideo.com", "jiosaavn.com", "jove.com",
    "jr.brainpop.com", "jupiter.err.ee", "kaltura.com", "kankanews.com", "karaoketv.co.il", "khabar.ndtv.com",
    "khanacademy.org", "kick.com", "kicker.de", "kickstarter.com", "kika.de", "kinopoisk.ru",
    "krasview.ru", "kuwo.cn", "la7.it", "ladigitale.dev", "laracasts.com", "last.fm",
    "latvijasradio.lsm.lv", "laxarxames.cat", "lbry.tv", "lcp.fr", "le.com", "learn.microsoft.com",
    "learningonscreen.ac.uk", "lecture2go.uni-hamburg.de", "lecturio.de", "lego.com", "leitv.it", "lemonde.fr",
    "lenta.ru", "life.ru", "likee.video", "lindicemcsween.telequebec.tv", "link.theplatform.com", "linkedin.com",
    "liputan6.com", "list.youku.com", "listennotes.com", "litv.tv", "live.aliexpress.com", "live.bilibili.com",
    "live.eplus.jp", "live.erinn.biz", "live.fc2.com", "live.huffingtonpost.com", "live.nicovideo.jp", "live.rbg.tum.de",
    "livestreamfails.com", "livr.jp", "lnk.lt", "loc.gov", "locipo.jp", "loco.com",
    "loom.com", "lovehomeporn.com", "lrt.lt", "ltv.lsm.lv", "lumni.fr", "lut-my.sharepoint.com",
    "magellantv.com", "magentamusik.de", "maison.radiofrance.fr", "manyvids.com", "maoritelevision.com", "markiza.sk",
    "massengeschmack.tv", "masters.com", "matchi.tv", "matchtv.ru", "mbn.co.kr", "mdr.de",
    "mdstrm.com", "me.ign.com", "medal.tv", "media.ccc.de", "media.cms.nova.cz", "media.joj.sk",
    "media.netapp.com", "media.photobucket.com", "media.rtvc.gov.co", "mediaite.com", "mediaklikk.hu", "mediasetinfinity.mediaset.it",
    "medici.tv", "medius.microsoft.com", "megatv.com", "meipai.com", "mellow-fan.com", "members.kelbyone.com",
    "members.nubiles-porn.com", "members.onepeloton.com", "metacritic.com", "mewatch.sg", "mgtv.com", "microsoft.com",
    "minds.com", "mir24.tv", "mirrativ.com", "mirror.co.uk", "mixch.tv", "mixcloud.com",
    "mlb.com", "mlssoccer.app.box.com", "mlssoccer.com", "mojevideo.sk", "monster-siren.hypergryph.com", "monstercat.com",
    "motherless.com", "motorsport.com", "moviefap.com", "moviepilot.de", "movingimage.nls.uk", "mp3.zing.vn",
    "msite.misis.ru", "msn.com", "mtv.com", "mtv.fi", "mtvuutiset.fi", "muenchen.tv",
    "mujrozhlas.cz", "multimedia.europarl.europa.eu", "murrtube.net", "muse.ai", "musescore.com", "music.163.com",
    "music.apple.com", "music.yandex.ru", "music.youtube.com", "mx3.ch", "mxplayer.in", "my.mail.ru",
    "mycanal.fr", "myspace.com", "myspass.de", "myvideo.ge", "myvidster.com", "mzaalo.com",
    "n-joy.de", "n-tv.de", "nationalgeographic.com", "nba.com", "nbc.com", "nbclosangeles.com",
    "nbcnews.com", "nbcolympics.com", "nbcsports.com", "ndr.de", "ndr2.radio.de", "nebula.tv",
    "nekohacker.com", "neo.mx3.ch", "netplus.tv", "netzkino.de", "new.godresource.com", "newgrounds.com",
    "news.cgtn.com", "news.cts.com.tw", "news.sky.com", "news.sportbox.ru", "news.yahoo.co.jp", "news.yahoo.com",
    "newspicks.com", "newsy.com", "nfb.ca", "nfhsnetwork.com", "nfl.com", "nhk.or.jp",
    "nhl.com", "nick.com", "nicochannel.jp", "nicovideo.jp", "ninaprotocol.com", "nintendo.com",
    "nitter.drivet.xyz", "nobelprize.org", "nokiatune.audiodraft.com", "nonktube.com", "nos.nl", "nowcanal.pt",
    "nowness.com", "noz.de", "npo.nl", "npr.org", "nrk.no", "nrl.com",
    "nts.live", "ntv.ru", "nuvid.com", "nytimes.com", "nzherald.co.nz", "nzonscreen.com",
    "nzz.ch", "oc-video1.ruhr-uni-bochum.de", "ochenlichnoe.mave.digital", "ocw.mit.edu", "odysee.com", "of.tv",
    "ok.ru", "oktoberfest-tv.de", "olympics.com", "omny.fm", "omroepwnl.nl", "on.orf.at",
    "ondemandchina.com", "ondemandkorea.com", "onefootball.com", "oneplace.com", "onet.tv", "open.noice.id",
    "openrec.tv", "oslo.kommunetv.no", "outsidetv.com", "packtpub.com", "palcomp3.com", "palcomp3.com.br",
    "pandalive.co.kr", "paramountpressexpress.com", "parler.com", "parliamentlive.tv", "parti.com", "patreon.com",
    "pbs.org", "pbskids.org", "peacocktv.com", "pearvideo.com", "peekvids.com", "peer.tv",
    "peertube.debian.social", "periscope.tv", "pgatour.com", "philharmoniedeparis.fr", "phoenix.de", "piapro.jp",
    "picarto.tv", "pilot.wp.pl", "pinkbike.com", "pinterest.ca", "pinterest.com", "platform.wim.tv",
    "platzi.com", "play.caracoltv.com", "play.kth.se", "play.lcp.fr", "play.nova.bg", "play.sooplive.com",
    "play.telecaribe.co", "play.tv", "play.tv2bornholm.dk", "play.tv3.lt", "player-api.p.uliza.jp", "player.bfi.org.uk",
    "player.bilibili.com", "player.daystar.tv", "player.fm", "player.glomex.com", "player.maariv.co.il", "player.mais.uol.com.br",
    "player.mangomolo.com", "player.megaphone.fm", "player.performgroup.com", "player.pia-live.jp", "player.piksel.tech", "player.polskieradio.pl",
    "player.radiozet.pl", "player.sky.it", "player.stv.tv", "player.tnaflix.com", "player.videoken.com", "player.waly.tv",
    "player.youku.com", "player.zype.com", "player02.getcourse.ru", "players.brightcove.net", "players.streaks.jp", "playout.3qsdn.com",
    "playsuisse.ch", "playtvak.cz", "playvids.com", "pluralsight.com", "pluto.tv", "podbay.fm",
    "podcasts.apple.com", "podcasty.polskieradio.pl", "podchaser.com", "pokergo.com", "polsatgo.pl", "polskieradio.pl",
    "popcorntimes.tv", "pornbox.com", "pornerbros.com", "pornflip.com", "pornhub.com", "pornotube.com",
    "pornovoisines.com", "pornoxo.com", "porntop.com", "porntube.com", "pr0gramm.com", "prankcast.com",
    "prehravac.rozhlas.cz", "premiershiprugby.com", "presstv.ir", "prima.iprima.cz", "programs.sbs.co.kr", "projectveritas.com",
    "puhutv.com", "pyvideo.org", "q-dance.com", "qingting.fm", "quantum-tv.com", "rad.live",
    "radiko.jp", "radio.nrk.no", "radio1.be", "radiofrance.fr", "radiojavan.com", "radiokapital.pl",
    "radioradicale.it", "radiothek.orf.at", "raicultura.it", "rainews.it", "raiplay.it", "raiplaysound.it",
    "raisport.rai.it", "raisudtirol.rai.it", "raywenderlich.com", "rctiplus.com", "rds.ca", "redbull.com",
    "redbull.tv", "reddit.com", "redgifs.com", "redtube.com", "ren.tv", "replay.lsm.lv",
    "restudy.dk", "retrocrush.tv", "reuters.com", "reverbnation.com", "ridehome.info", "rinse.fm",
    "rockstargames.com", "rokfin.com", "roosterteeth.com", "rottentomatoes.com", "rss.art19.com", "rt.com",
    "rtbf.be", "rtd.rt.com", "rte.ie", "rtl.lu", "rtl2.de", "rtlxl.nl",
    "rtp.pt", "rtrfm.com.au", "rts.ch", "rtvcplay.co", "rtve.es", "rtvs.sk",
    "rtvslo.si", "rudo.video", "ruhr-uni-bochum.sciebo.de", "rule34video.com", "rumble.com", "ruptly.tv",
    "rutube.ru", "ruutu.fi", "ruv.is", "s4c.cymru", "safaribooksonline.com", "saitosan.net",
    "saktv.ch", "samplefocus.com", "sauceplus.com", "sbs.com.au", "schooltv.nl", "sciencechannel.com",
    "scienceteachingtips.podomatic.com", "screencast-o-matic.com", "screencast.com", "screenrec.com", "scrolller.com", "secure.nba.com",
    "sejm.gov.pl", "sen.com", "senalcolombia.tv", "senate.gov", "servustv.com", "sexu.com",
    "seznamzpravy.cz", "shahid.mbc.net", "share.glide.me", "share.onsen.ag", "shemaroome.com", "shiey.com",
    "showroom-live.com", "shows.acast.com", "shugiintv.go.jp", "skeb.jp", "skylinewebcams.com", "skynews.com.au",
    "skynewsarabia.com", "skysports.com", "slideshare.net", "slideslive.com", "slutload.com", "smotrim.ru",
    "snagfilms.com", "snapchat.com", "softwhiteunderbelly.com", "sonyliv.com", "sooplive.com", "sound.orf.at",
    "soundcloud.com", "soundgasm.net", "southpark.cc.com", "southpark.de", "southpark.lat", "southparkstudios.co.uk",
    "southparkstudios.com.br", "southparkstudios.nu", "sovietscloset.com", "space.bilibili.com", "spankbang.com", "spiegel.de",
    "sport.sky.it", "sporteurope.tv", "sportklub.n1info.rs", "sports.cntv.cn", "squat.telequebec.tv", "sr-mediathek.de",
    "srf.ch", "stacommu.jp", "stage-plus.com", "startrek.com", "startv.com.tr", "steamcommunity.com",
    "store.steampowered.com", "storyfire.com", "stream.nbcolympics.com", "stream.nbcsports.com", "stream.new", "stream.tvp.pl",
    "streamable.com", "streams.bitmovin.com", "streetvoice.com", "stripchat.com", "subsplash.com", "suncity-104-9fm.mixlr.com",
    "sunporno.com", "sverigesradio.se", "svt.se", "svtplay.se", "swipeto.pl", "syfy.com",
    "sztv.hu", "t-online.de", "t.bilibili.com", "t.me", "t13.cl", "tagesschau.de",
    "taptap.cn", "taptap.io", "tarangplus.in", "tass.ru", "tatianamaslanydaily.tumblr.com", "tbs.com",
    "teachertube.com", "teachingchannel.org", "teamcoco.com", "teamtreehouse.com", "techtv.mit.edu", "ted.com",
    "tegenlicht.vpro.nl", "tele-task.de", "tele5.de", "telecinco.es", "telegraaf.nl", "telemb.be",
    "telemundo.com", "televizeseznam.cz", "telewebion.ir", "tennistv.com", "tf1.fr", "tf1info.fr",
    "tfo.org", "the-re-bind-io-podcast.simplecast.com", "theater-complex.town", "theepochtimes.com", "theguardian.com", "thehighwire.com",
    "theintercept.com", "thestar.com", "thesun.co.uk", "theverge.com", "thisamericanlife.org", "thisoldhouse.com",
    "thisvid.com", "tiktok.com", "tmz.com", "tn.nova.cz", "tnaflix.com", "toggo.de",
    "toongoggles.com", "toutiao.com", "tp.srgssr.ch", "trtcocuk.net.tr", "trtworld.com", "trueid.id",
    "trunews.com", "truthsocial.com", "tube.tugraz.at", "tube8.com", "tubitv.com", "tun.in",
    "tunein.com", "tv.biobiochile.cl", "tv.dfb.de", "tv.jtbc.co.kr", "tv.kakao.com", "tv.nate.com",
    "tv.naver.com", "tv.nrk.no", "tv.r7.com", "tv.salt.ch", "tv.sohu.com", "tv.telezueri.ch",
    "tv2.no", "tv2play.hu", "tv4.se", "tv5monde.com", "tv5unis.ca", "tv8.it",
    "tvanouvelles.ca", "tvaplus.ca", "tvc.ru", "tver.jp", "tvigle.ru", "tviplayer.iol.pt",
    "tvn24.pl", "tvnoe.cz", "tvo.org", "tvonline.ewe.de", "tvonline.osnatel.de", "tvp.pl",
    "tvplay.lv", "tvplus.m-net.de", "tvpot.daum.net", "tvsyd.dk", "tvw.org", "tweakers.net",
    "twitcasting.tv", "twitch.tv", "twitter.com", "txxx.com", "udemy.com", "uk.businessinsider.com",
    "ukcolumn.org", "ulizaportal.jp", "ultimedia.com", "unity3d.com", "universal-music.de", "urort.p3.no",
    "urplay.se", "us-lti.bbcollab.com", "usanetwork.com", "usatoday.com", "ustream.tv", "ustudio.com",
    "utv.unistra.fr", "uvp.apa.at", "v.baidu.com", "v.douyu.com", "v.ku6.com", "v.qq.com",
    "v1.upskillcourses.com", "vbox7.com", "vevo.com", "vgtv.no", "vh1.com", "vice.com",
    "vid.ly", "viddler.com", "videa.hu", "video-api.wsj.com", "video.aktualne.cz", "video.arnes.si",
    "video.corriere.it", "video.disney.com", "video.fc2.com", "video.foxnews.com", "video.glomex.com", "video.golem.de",
    "video.hockeycanada.ca", "video.kenh14.vn", "video.kompas.com", "video.lastampa.it", "video.lefigaro.fr", "video.mocha.com.vn",
    "video.nest.com", "video.rcs.it", "video.sina.com.cn", "video.sky.it", "video.telequebec.tv", "video.tv.adobe.com",
    "video.twentythree.net", "video.udn.com", "video.varzesh3.com", "video.vice.com", "video.wired.com", "videoarchiv.markiza.sk",
    "videocampus.sachsen.de", "videolectures.net", "videopress.com", "videos.r7.com", "videos.sapo.pt", "videos.sproutvideo.com",
    "videos.toypics.net", "vidio.com", "vidlii.com", "vimeo.com", "vimeopro.com", "vimp.oth-regensburg.de",
    "visir.is", "viu.com", "vk.com", "vkplay.live", "vocaroo.com", "vod-platform.net",
    "vod.graspop.be", "vod.melon.com", "vod.sooplive.com", "vod.sport5.co.il", "vod.tvp.pl", "vod.walla.co.il",
    "vodupload-api.mediaworks.nz", "voicy.jp", "volej.tv", "volksmusik.mx3.ch", "volume.vox-cdn.com", "vplayer.nbcsports.com",
    "vrt.be", "vtm.be", "vtv.vn", "vtvgo.vn", "vtxtv.ch", "vyexample03.hubs.vidyard.com",
    "w.soundcloud.com", "warszawa-plac-zamkowy.webcamera.pl", "washingtonpost.com", "wat.tv", "watch.cookingchanneltv.com", "watch.dropout.tv",
    "watch.foodnetwork.com", "watch.geniuskitchen.com", "watch.hgtv.com", "watch.historyvault.com", "watch.islamchannel.tv", "watch.nba.com",
    "watch.screencastify.com", "watch.thechosen.tv", "watch.travelchannel.com", "wave.rozhlas.cz", "wdrmaus.de", "weather.com",
    "web.arbeitsagentur.de", "web.archive.org", "webofstories.com", "webtools-e18da6642b684f8aa9ae449862783a56.msvdn.net", "webtv.sangiin.go.jp", "webtv.un.org",
    "weibo.com", "weiqitv.com", "wetv.vip", "weverse.io", "wevidi.net", "whowatch.tv",
    "whyp.it", "wimbledon.com", "winsports.co", "worldstarhiphop.com", "wrestle-universe.com", "wsj.com",
    "wwe.com", "www1.wdr.de", "www2.nhk.or.jp", "www3.nhk.or.jp", "wyborcza.pl", "wykop.pl",
    "x-minus.org", "xboxclips.com", "xhamster.com", "xiaohongshu.com", "ximalaya.com", "xinpianchang.com",
    "xnxx.com", "xvideos.com", "xxxymovies.com", "y.qq.com", "yadi.sk", "yandex.ru",
    "yapfiles.ru", "yappy.media", "yfanefa.com", "yinyue.kuwo.cn", "youjizz.com", "younow.com",
    "youporn.com", "youtu.be", "youtube-dl.bandcamp.com", "youtube.com", "zaiko.io", "zan-live.com",
    "zapiks.fr", "zattoo.com", "zdf.de", "zeenews.india.com", "zen.yandex.ru", "zenporn.com",
    "zetland.dk", "zhihu.com", "zingmp3.vn", "zonevideo.telequebec.tv", "zoom.us",
    ]
}
